### ISSUE TITLE
运行代码报错

### ISSUE THREAD

**Issue by sniperXue** [Paleozoic/storm_spring_boot_demo#8]
直接运行你的代码发现下面错误；本地如何跑通，求解！！！
java.lang.NoClassDefFoundError: org/apache/storm/generated/InvalidTopologyException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.generated.InvalidTopologyException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"

**Comment by Paleozoic** [comment]
根据报错请检查对应的jar包是否引入。

**Comment by sniperXue** [comment]
应该如何把拓扑提交给storm集群呢？ storm jar StormDemo.jar com.maxplus1.DemoApplication 提示的加载不到那个类（我是在Docker上的集群中运行）

**Comment by Paleozoic** [comment]
#5

**Comment by sniperXue** [comment]
运行的时候出现如下错误：
INFO main (DefaultLifecycleProcessor.java:358) - Stopping beans in phase 2147483647
2019-02-18 14:45:11,707:INFO main (DefaultLifecycleProcessor.java:358) - Stopping beans in phase 0
2019-02-18 14:45:11,718:INFO main (MBeanExporter.java:449) - Unregistering JMX-exposed beans on shutdown
2019-02-18 14:45:11,731:WARN main (DisposableBeanAdapter.java:374) - Invocation of destroy method 'close' failed on bean with name 'kafkaSpout': java.lang.NullPointerException
2019-02-18 14:45:11,738:WARN main (DisposableBeanAdapter.java:374) - Invocation of destroy method 'close' failed on bean with name 'kafkaClientSpout': java.lang.NullPointerException
2019-02-18 14:45:11,743:INFO main (ExecutorConfigurationSupport.java:203) - Shutting down ExecutorService
